### ISSUE TITLE
Limit on subfolders displayed

### ISSUE THREAD

**Issue by SowmyaMastaiah** [mpobjects/s3index#1]
Hi,

index.html displays nicely the content of S3 Bucket although there is a limit on subfolders getting displayed. Only random 1000 number of folders gets displayed.

Thanks,
Sowmya

**Comment by elmuerte** [comment]
AWS returns up to a 1000 entries per request. In the new version a "load more" action is available at the bottom of the list to load the next 1000 entries. As the listing will be re-rendered and sorted new items can show up anywhere on the page. 
The order of retrieved entries cannot be controlled.
